import { Mail, MapPin, MessageCircle, Send } from "lucide-react";
import { socials, services, whatsapp } from "@/data/portfolio";
import { Button } from "@/components/ui/button";
import { Reveal } from "./Reveal";

export function Contact({ initialService = "" }: { initialService?: string }) {
  return <section id="contact" className="px-4 py-20 sm:px-6 md:py-28"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]">
    <Reveal className="surface-elevated rounded-lg border p-6 sm:p-8"><p className="section-kicker">Project inquiry</p><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">Let&apos;s Work Together</h2><p className="mt-3 text-muted-foreground">Share the project essentials below. Submitting opens your email app with the details ready to send.</p>
      <form action="mailto:hello@zehraaisolutions.com" method="post" encType="text/plain" className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-medium">Name<input name="Name" required autoComplete="name" className="form-control" placeholder="Your name" /></label><label className="grid gap-2 text-sm font-medium">Email<input name="Email" type="email" required autoComplete="email" className="form-control" placeholder="you@company.com" /></label><label className="grid gap-2 text-sm font-medium">Service<select name="Service" required defaultValue={initialService} className="form-control"><option value="" disabled>Select a service</option>{services.map((service) => <option key={service.title}>{service.title}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Project Details<textarea name="Project Details" required rows={6} className="form-control resize-none" placeholder="Tell me about your goals, audience and required pages or features." /></label><Button type="submit" size="lg"><Send /> Send Project Inquiry</Button></form>
    </Reveal>
    <Reveal delay={0.1} className="grid content-start gap-4"><a href="mailto:hello@zehraaisolutions.com" className="contact-row"><span className="icon-tile"><Mail /></span><span className="min-w-0"><span className="block text-xs uppercase text-muted-foreground">Professional email</span><span className="block truncate font-semibold">hello@zehraaisolutions.com</span></span></a><a href={whatsapp.href} target="_blank" rel="noopener noreferrer" className="contact-row"><span className="icon-tile"><MessageCircle /></span><span><span className="block text-xs uppercase text-muted-foreground">WhatsApp Business</span><span className="font-semibold">{whatsapp.display}</span></span></a><div className="contact-row"><span className="icon-tile"><MapPin /></span><span><span className="block text-xs uppercase text-muted-foreground">Location</span><span className="font-semibold">Pakistan</span></span></div><div className="surface-elevated rounded-lg border p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">Connect</p><div className="mt-4 flex flex-wrap gap-2">{socials.map((social) => <Button key={social.label} asChild variant="outline" size="sm"><a href={social.href} target="_blank" rel="noopener noreferrer">{social.icon ? <social.icon /> : null}{social.label}</a></Button>)}</div></div></Reveal>
  </div></section>;
}